// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3CL7daxrUSdjngwYCIOzOZ1x_Kv-BgNA',
    appId: '1:214698772452:web:63ae07ff98cc75aea9a9f1',
    messagingSenderId: '214698772452',
    projectId: 'zunghubapp-b33f6',
    authDomain: 'zunghubapp-b33f6.firebaseapp.com',
    storageBucket: 'zunghubapp-b33f6.firebasestorage.app',
    measurementId: 'G-ZRF9Y8133T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClEUPcJb0u5nSKaRyfopT3_Gy5iHR7QiA',
    appId: '1:214698772452:android:9692450de9c881a9a9a9f1',
    messagingSenderId: '214698772452',
    projectId: 'zunghubapp-b33f6',
    storageBucket: 'zunghubapp-b33f6.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBArbVinL9t-vRNzuX60iODvb7T8PS04eA',
    appId: '1:214698772452:ios:90ecbe36dade7dd5a9a9f1',
    messagingSenderId: '214698772452',
    projectId: 'zunghubapp-b33f6',
    storageBucket: 'zunghubapp-b33f6.firebasestorage.app',
    iosBundleId: 'com.example.zunghub',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBArbVinL9t-vRNzuX60iODvb7T8PS04eA',
    appId: '1:214698772452:ios:90ecbe36dade7dd5a9a9f1',
    messagingSenderId: '214698772452',
    projectId: 'zunghubapp-b33f6',
    storageBucket: 'zunghubapp-b33f6.firebasestorage.app',
    iosBundleId: 'com.example.zunghub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB3CL7daxrUSdjngwYCIOzOZ1x_Kv-BgNA',
    appId: '1:214698772452:web:3c95f6575a21570ca9a9f1',
    messagingSenderId: '214698772452',
    projectId: 'zunghubapp-b33f6',
    authDomain: 'zunghubapp-b33f6.firebaseapp.com',
    storageBucket: 'zunghubapp-b33f6.firebasestorage.app',
    measurementId: 'G-QLYTWK8CXW',
  );
}
